name:  Greetings

on:  [pull_request, issues]
permissions:
  pull-requests:  write
  issues:  write
jobs:
  greeting:
    runs-on:  ubuntu-latest
    steps:
    - uses:  actions/first-interaction@v1
      with:
        repo-token:  ${{  secrets.GITHUB_TOKEN  }}
        issue-message:  |
          # Message with markdown
          Onneksi olkoon ensimmäisestä issuesta!
        pr-message:  |
          # Message that will be displayed on users' first pr.
          Teit ensimmäisen Pull Requestin!
